### ISSUE TITLE
Multiple logstash instances reading from same kinesis stream

### ISSUE THREAD

**Issue by alexanderfichel** [codekitchen/logstash-input-kinesis#10]
Wasn't sure where or how to ask you this, but if I have multiple logstash instances reading from the same kinesis stream, would I get duplicates? I am basing this on my understanding of the redis -> logstash model. Right now I have multiple logstash instances reading from one redis cluster, and seems like there is some type of read lock to prevent duplicate reads, and I was wondering if this has the same capability.

**Comment by codekitchen** [comment]
This is handled by the [KCL](https://github.com/awslabs/amazon-kinesis-client) -- basically if the logstash instances have the same `application_name` parameter set for this plugin, they'll balance the load and not see duplicates. If they have different application names, they'll read from the kinesis stream independently.

**Comment by alexanderfichel** [comment]
Great @codekitchen ! Really appreciate your reply :) Thank you.
