### ISSUE TITLE
Error processing record.getData: java.nio.HeapByteBuffer[pos=0 lim=611 cap=611]

### ISSUE THREAD

**Issue by mataneine** [codekitchen/logstash-input-kinesis#2]
Any idea why we get this error when trying to use the plugin?

:message=>"Error processing record.getData: java.nio.HeapByteBuffer[pos=0 lim=611 cap=611]", :level=>:error, :file=>"logstash/inputs/kinesis/worker.rb", :line=>"68", :method=>"process_record"

Thanks

**Comment by codekitchen** [comment]
hm, strange that it reports the error on line 68, record.getData should be on line 48. have you modified the file at all?

There's not much in the error message to go on, but maybe an out of memory condition.

**Comment by mataneine** [comment]
I modified the file after I saw the errors and added logs to it, trying to understand whats going on because  it didn't manage to process any record, and I can see the records in Kinesis and decode them in cli.
I don't know if its related but amazon-kinesis-client is already at v1.6.0 http://mvnrepository.com/artifact/com.amazonaws/amazon-kinesis-client/1.6.0

**Comment by Infra-dev** [comment]
Guys i have same issue, fighting with it third day....
Please help

{:timestamp=>"2015-09-09T08:53:09.112000+0000", :message=>"Error processing record: Input
length = 1", :level=>:error, :file=>"logstash/inputs/kinesis/worker.rb", :line=>"54", :met
hod=>"process_record"}

I checked kinesis stream, data exist.
Btw, i tried also cwl-consummer, their code has 2 steps of message decode: Base64 and after unzip.
But here in code i don't see such a step. Maybe it is related to?
p.s.
sorry if so, I'm not a guru in ruby & java. Just need to make all this chain work.

**Comment by codekitchen** [comment]
I've yet to see this myself, so my ability to debug it is pretty limited so far.

**Comment by dsolsona** [comment]
I'm having the same issue with logstash 1.5.4-1 and the logstash kinesis input 1.3.1

I believe the issue when you call `@decoder.decode` for some records in https://github.com/codekitchen/logstash-input-kinesis/blob/master/lib/logstash/inputs/kinesis/worker.rb#L48

I did some changes to the code to see if that was the case

```
 49   def process_record(record)
 50     begin
 51         raw = @decoder.decode(record.getData).to_s
 52         @logger.error("Decoded record: #{raw} raw:(#{record.getData})")
 53
 54         @codec.decode(raw) do |event|
 55           @logger.error("New event: #{event}")
 56           @decorator.call(event)
 57           @output_queue << event
 58         end
 59     rescue => e
 60         @logger.error("Failed to decode record (#{record.getData}) because of error #{e}")
 61     end
 62   #rescue => error
 63   #  @logger.error("Error processing record: #{error}")
 64   end
 65 end
```

And then this is the output I got

```
Failed to decode record (java.nio.HeapByteBuffer[pos=0 lim=37721 cap=37721]) because of error Input length = 3 {:level=>:error}
Failed to decode record (java.nio.HeapByteBuffer[pos=0 lim=38150 cap=38150]) because of error Input length = 3 {:level=>:error}
Failed to decode record (java.nio.HeapByteBuffer[pos=0 lim=38512 cap=38512]) because of error Input length = 3 {:level=>:error}
Decoded record: {"host":"localhost","message":"smtp: Failed: Connect failed","offset":150456472,"path":"/var/log/system.log","type":"syslog","@version":"1","@timestamp":"2015-09-20T08:45:55.000Z","tags":["syslog"],"syslog_timestamp":"Sep 20 03:45:55","syslog_hostname":"localhost","syslog_program":"nullmailer"} raw:(java.nio.HeapByteBuffer[pos=357 lim=357 cap=357]) {:level=>:error}
New event: 2015-09-20T08:45:55.000Z localhost smtp: Failed: Connect failed {:level=>:error}
Failed to decode record (java.nio.HeapByteBuffer[pos=0 lim=15092 cap=15092]) because of error Input length = 3 {:level=>:error}
Failed to decode record (java.nio.HeapByteBuffer[pos=0 lim=6971 cap=6971]) because of error Input length = 3 {:level=>:error}
Failed to decode record (java.nio.HeapByteBuffer[pos=0 lim=3848 cap=3848]) because of error Input length = 3 {:level=>:error}
```

My kinesis output is configured to send all the evens in json with UTF-8 charset, I'm not sure why some events fail to be decoded and why some others work.

**Comment by samuelgmartinez** [comment]
@dsolsona what kinesis producer version are you using to send the messages to kinesis? 

We hit a very similar problem related to producer aggregation. Since this input plugin uses an old client library (v1.2.1) which doesn't support message aggregation, you can't deserialize the messages you are receiving. 

We fixed that just upgrading and repackaging the libraries. I'll make a PR asap.

**Comment by dsolsona** [comment]
@samuelgmartinez I'm using https://github.com/samcday/logstash-output-kinesis which seems to have record aggregation enabled by default and now that you mention I can see this input-kinesis failing just on events that have several records.

You nailed it :) thanks for the help. I'll disable aggregation and will try again once your pull request gets merged.
