### ISSUE TITLE
Logs missing in ES when aggregating logs

### ISSUE THREAD

**Issue by rhoml** [codekitchen/logstash-input-kinesis#9]
At the moment we are using https://github.com/samcday/logstash-output-kinesis to ingest logs into kinesis and we discovered today that many logs are missing if we use https://github.com/samcday/logstash-output-kinesis#record-aggregation. Once we disable log aggregation ingestion works as expected but ingestion get too slow ~2 hours delay.

It is also to notice than the cloudwatch metric for user pending records is at 20k records if aggregation is on, while it starts to get emptier when aggregation is disabled.

Our question is if this is related to the output or the input which we haven't been able to debug yet in a reliable way.

c/ @samcday

**Comment by codekitchen** [comment]
Aggregation isn't yet supported in this input plugin, see the discussion in #6 

It shouldn't be too hard to add support, but nobody has done the work yet.

**Comment by rhoml** [comment]
Oh thanks i didn't dig into the code yesterday.

**Comment by rhoml** [comment]
I am going to go ahead and close this issue then.
